name: Build website

on:
  push:
    branches: [main, release/*]
  pull_request:

jobs:
  build:
    name: "build foxglove"
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
        with:
          lfs: true

      - name: setup node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16.17

      - name: enable corepack
        run: corepack enable yarn

      - name: install dependencies
        run: |
          yarn install --immutable

      - name: build project
        run: |
          yarn run web:build:prod

      - name: compress build artifacts
        run: tar -czf web-build.tar.gz -C web/.webpack .

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: web-build.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
